name: Publish Factorio Mod

on:
    push:
        branches:
            - master

jobs:
    publish-mod:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Validate Mod
              uses: TheBrutalX/factorio-mod-uploader-action@v1
              with:
                  action: validate

            - name: Create zip
              uses: TheBrutalX/factorio-mod-uploader-action@v1
              with:
                  action: compress

            - name: Upload Mod
              uses: TheBrutalX/factorio-mod-uploader-action@v1
              with:
                  action: upload
                  factorio-api-key: ${{ secrets.FACTORIO_API_KEY }}
